name: Build and deploy webassembly version
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build_webassembly_version:
    name: Build webassembly version
    runs-on: ubuntu-latest
    container: emscripten/emsdk:4.0.4
    permissions: write-all
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build fallout2 wasm module
        run: |
          git config --global --add safe.directory "*"
          mkdir -p build
          cd build
          emcmake cmake ../ -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/Emscripten.cmake -DCMAKE_BUILD_TYPE=Release && emmake make VERBOSE=1 -j 4
          cd ..

      - name: Add node
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Checkout web interface
        uses: actions/checkout@v4
        with:
          repository: ololoken/fallout2-ce-ems
          ref: 0764f9fdd0abf27bd9b0d3997ca0a8e61f380058
          path: fallout2-ce-ems

      - name: Set deployment path
        id: set-path
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "DEST_DIR=PR-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "SITE_BASE=/fallout2-ce/PR-${{ github.event.pull_request.number }}/" >> $GITHUB_OUTPUT
          else
            echo "DEST_DIR=." >> $GITHUB_OUTPUT
            echo "SITE_BASE=/fallout2-ce/" >> $GITHUB_OUTPUT
          fi
          echo ===============================
          cat $GITHUB_OUTPUT

      - name: Build web interface
        run: |
          cd fallout2-ce-ems
          npm install
          cp ../build/fallout2-ce.js src/assets/fallout2ce
          cp ../build/fallout2-ce.wasm src/assets/fallout2ce
          npm run build
        env:
          SITE_BASE:  ${{ steps.set-path.outputs.SITE_BASE }}

      - name: Deploy PR preview or main site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: fallout2-ce-ems/dist
          target-folder: ${{ steps.set-path.outputs.DEST_DIR }}
          clean: false

      - name: Comment preview URL on PR
        if: github.event_name == 'pull_request'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "🚀 WebAssembly PR Preview is available at: https://${{ github.repository_owner }}.github.io/fallout2-ce/PR-${{ github.event.pull_request.number }}/"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}