name: Build and deploy webassembly version
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build_webassembly_version:
    name: Build webassembly version
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.74
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build fallout2 wasm module
        run: |
          git config --global --add safe.directory "*"
          mkdir -p build
          cd build
          emcmake cmake ../ -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/Emscripten.cmake -DCMAKE_BUILD_TYPE=Release && emmake make VERBOSE=1 -j 4
          cd ..
          cp build/fallout2-ce.js fallout2-ce-emscripten-module/
          cp build/fallout2-ce.wasm fallout2-ce-emscripten-module/

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          branch: gh-pages-demo
          folder: build
