name: Cleanup PR Preview

on:
  pull_request:
    types:
      - closed

jobs:
  delete_pr_preview:
    name: Delete PR preview from gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove PR preview folder
        run: |
          PR_FOLDER="PR-${{ github.event.pull_request.number }}"
          echo "Removing preview folder: $PR_FOLDER"
          git rm -r --ignore-unmatch "$PR_FOLDER" || true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "🚮 Remove preview for closed PR #${{ github.event.pull_request.number }}"
          git push
